language: python
services:
  - mongodb
  - redis-server
matrix:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      python: 3.6
      env: DEPLOY=yes
    - name: "Python 3.7 on Xenial Linux"
      os: linux
      python: 3.7
      dist: xenial
      env: DEPLOY=yes
    - name: "Python on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - brew install redis
        - brew install mongodb
        - brew services start redis
        - brew services start mongodb
        - pip3 install -U pip
    - name: "Python on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - choco install mongodb
        - choco install redis-64
        - start redis-server
        - pip3 install --user -U pip
        - pip3 install --user coveralls
        - pip3 install --user pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:/c/ProgramData/chocolatey/lib/redis-64:$PATH
      after_script:
        - redis-cli shutdown
install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt
  - pip3 install pytest-cov
  - pip3 install coveralls
  - pip3 install -e .
before_script:
  - sleep 15
script:
  - pytest --cov=qulab --verbose
after_success:
  - coveralls
deploy:
  provider: pypi
  user: feihoo87
  password:
    secure: Ih0A1d1puzNsmbMHRF1vFGQixRs0wqDC93VZHYaW1tDDI0wGpidaKgHmm3vpHP+uJlQrtil/OUPv0xnQC5QCNX3I4fD6akr2QwYlYxvlbisHYZ5vOHSv/cVud5ezYaIz4dP1m/cbatf0K5YlaD92ETfNMwTzd4LmcPtihPgyq7u/6Az0yL+pfqRVsshmcQV/bAH8VvkPCYjZ/3nuQV9cKBHzP7ZbRzOI5z5pTv1oTlnGyhxczB1uKpY9GPcdLxZDyAeVcqG1Pnwdq1UUHve3aXAWTyPMG9I9EC4B33FgpQRj4gLhp0HeLs2glkQlfLapVbV6kWuFRoslYXB5Hh6l4zNasqhn8FUrU2yUFtJEnnatxNJ/7ZpnYuWS3CG9r+Mfu4IwF1L8iW++ogUW6nhwnwxPCZKMmvwlMvs2Q8kF4ikqbkL4ZBgPWv9qoKfkrvg2/AsUfTvzACICMaJ4CUBVEp8yOQWvguzvct/IbhGMqWhr5czW54HD5qBCudXAUI4TjZU5EBgFseckKidt7jWsYKKewj7krKPjpPPOwIUj8eA+QI0pWkijlFyzezghhDLKgxZLenS0IQkyrFuWvYz5C9fxYzFUZ/XKeKgEa10h5NUHMNjn9QLbES9qXEg2CTNfnB9LctmkMXg5zCICIVSCKB80jGDV2/eVYCK2jgdp+cg=
  on:
    branch: master
    tags: true
    condition: $DEPLOY = yes
  skip_existing: true
  skip_cleanup: true
  distributions: "sdist bdist_wheel"